/// <reference types="Cypress" />

it('Replenishment of Ukraine mobile phone number', ()=> {
    cy.visit('https://next.privat24.ua/mobile?lang=en')
        .get('[data-qa-node="phone-number"]')
        .type('686979712')
        .get('[data-qa-node="amount"]')
        .type('1')
        .get('[data-qa-node="numberdebitSource"]')
        .type('4552331448138217')
        .get('[data-qa-node="expiredebitSource"]')
        .type('0524')
        .get('[data-qa-node="cvvdebitSource"]')
        .type('111')
        .wait(3000)
        .get('[data-qa-node="submit"]')
        .click()
        .get('[data-qa-node="card"]')
        .should('have.text', '4552 **** **** 8217')
        .get('[data-qa-node="amount"]')
        .should('have.text', '1')
        .get('[data-qa-node="currency"]')
        .eq(0)
        .should('contain.text', 'UAH')
        .get('[data-qa-node="commission"]')
        .eq(1)
        .should('have.text', '2')
        .get('[data-qa-node="commission-currency"]')
        .should('contain.text', 'UAH')
})

it.only('money transfer between foreign cards', () => {
    cy.visit('https://next.privat24.ua/money-transfer/card?lang=en')
        .get('[data-qa-node="numberdebitSource"]')
        .type('4552331448138217')
        .get('[data-qa-node="expiredebitSource"]')
        .type('0524')
        .get('[data-qa-node="cvvdebitSource"]')
        .type('111')
        .get('[data-qa-node="firstNamedebitSource"]')
        .type('Shayne')
        .get('[data-qa-node="lastNamedebitSource"]')
        .type('McConnell')
        .get('[data-qa-node="numberreceiver"]')
        .type('5309233034765085')
        .get('[data-qa-node="firstNamereceiver"]')
        .type('Juliana')
        .get('[data-qa-node="lastNamereceiver"]')
        .type('Jansen')
        .get('[data-qa-node="amount"]')
        .type('300')
        .get('[data-qa-node="toggle-comment"]')
        .click()
        .get('[data-qa-node="comment"]')
        .type('cypress test')
        .get('button[type="submit"]')
        .click()
        .get('[data-qa-node="payer-card"]')
        .should('have.text', '* 8217')
        .get('[data-qa-node="receiver-card"]')
        .should('have.text', '* 5085')
        .get('[data-qa-node="payer-amount"]')
        .should('have.text', '300 UAH')
        .get('[data-qa-node="payer-currency"]')
        .should('have.text', '89.10 UAH')
        .get('[data-qa-node="total"]')
        .find('span')
        .should('contains.text', '389.10')
        .get('[data-qa-node="total"]')
        .find('small')
        .should('contains.text', 'UAH')
})








